// Code generated by thriftrw-plugin-yarpc
// @generated

package storeclient

import (
	context "context"
	fmt "fmt"
	wire "go.uber.org/thriftrw/wire"
	yarpc "go.uber.org/yarpc"
	encoding "go.uber.org/yarpc/api/encoding"
	transport "go.uber.org/yarpc/api/transport"
	thrift "go.uber.org/yarpc/encoding/thrift"
	atomic "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/atomic"
	readonlystoreclient "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/atomic/readonlystoreclient"
	encoding2 "go.uber.org/yarpc/pkg/encoding"
	procedure "go.uber.org/yarpc/pkg/procedure"
	reflect "reflect"
)

// Interface is a client for the Store service.
type Interface interface {
	readonlystoreclient.Interface

	CompareAndSwap(
		ctx context.Context,
		Request *atomic.CompareAndSwap,
		opts ...yarpc.CallOption,
	) error

	Forget(
		ctx context.Context,
		Key *string,
		opts ...yarpc.CallOption,
	) (yarpc.Ack, error)

	Increment(
		ctx context.Context,
		Key *string,
		Value *int64,
		opts ...yarpc.CallOption,
	) error
}

// New builds a new client for the Store service.
//
// 	client := storeclient.New(dispatcher.ClientConfig("store"))
func New(c transport.ClientConfig, opts ...thrift.ClientOption) Interface {
	return client{
		c: thrift.New(thrift.Config{
			Service:      "Store",
			ClientConfig: c,
		}, opts...),
		adapterProvider: encoding.NopAdapterProvider,

		Interface: readonlystoreclient.New(
			c,
			append(
				opts,
				thrift.Named("Store"),
			)...,
		),
	}
}

// Config is a forwards compatible configuration struct for the Store service.
type Config struct {
	AdapterProvider encoding.AdapterProvider
}

// NewFromConfig builds a new client for the Store service.
func NewFromConfig(cc transport.ClientConfig, cfg Config, opts ...thrift.ClientOption) (Interface, error) {
	const thriftService = "Store"

	thriftClient := thrift.New(thrift.Config{
		Service:      thriftService,
		ClientConfig: cc,
	}, opts...)

	if cfg.AdapterProvider == nil {
		cfg.AdapterProvider = encoding.NopAdapterProvider
	}
	adapterClient, err := encoding2.NewAdapterClient(
		encoding2.AdapterClientConfig{
			ClientConfig: cc,
		},
	)
	if err != nil {
		return nil, err
	}

	return client{
		c:             thriftClient,
		adapterClient: adapterClient,

		Interface: readonlystoreclient.New(
			cc,
			append(
				opts,
				thrift.Named("Store"),
			)...,
		),

		thriftService:   thriftService,
		cc:              cc,
		adapterProvider: cfg.AdapterProvider,
	}, nil
}

func init() {
	yarpc.RegisterClientBuilder(
		func(c transport.ClientConfig, f reflect.StructField) Interface {
			return New(c, thrift.ClientBuilderOptions(c, f)...)
		},
	)
}

type client struct {
	readonlystoreclient.Interface

	c               thrift.Client
	adapterClient   encoding2.AdapterClient
	thriftService   string
	cc              transport.ClientConfig
	adapterProvider encoding.AdapterProvider
}

func (c client) CompareAndSwap(
	ctx context.Context,
	_Request *atomic.CompareAndSwap,
	opts ...yarpc.CallOption,
) (err error) {

	args := atomic.Store_CompareAndSwap_Helper.Args(_Request)
	procedureName := procedure.ToName(c.thriftService, args.MethodName())

	var result atomic.Store_CompareAndSwap_Result

	if adapter, ok := c.adapterProvider.Adapter(procedureName); ok {
		tReq := &transport.Request{
			Caller:    c.cc.Caller(),
			Service:   c.cc.Service(),
			Encoding:  thrift.Encoding,
			Procedure: procedureName,
		}
		res, err := c.adapterClient.Call(ctx, tReq, args, adapter, opts...)
		if err != nil {
			return err
		}

		var ok bool
		result, ok = res.(atomic.Store_CompareAndSwap_Result)
		if !ok {
			return fmt.Errorf("thrift adapter returned invalid type for procedure, expected 'atomic.Store_CompareAndSwap_Result', got '%T'", res)
		}

	} else {

		var body wire.Value
		body, err = c.c.Call(ctx, args, opts...)
		if err != nil {
			return
		}

		if err = result.FromWire(body); err != nil {
			return
		}
	}

	err = atomic.Store_CompareAndSwap_Helper.UnwrapResponse(&result)
	return
}

func (c client) Forget(
	ctx context.Context,
	_Key *string,
	opts ...yarpc.CallOption,
) (yarpc.Ack, error) {
	args := atomic.Store_Forget_Helper.Args(_Key)
	return c.c.CallOneway(ctx, args, opts...)
}

func (c client) Increment(
	ctx context.Context,
	_Key *string,
	_Value *int64,
	opts ...yarpc.CallOption,
) (err error) {

	args := atomic.Store_Increment_Helper.Args(_Key, _Value)
	procedureName := procedure.ToName(c.thriftService, args.MethodName())

	var result atomic.Store_Increment_Result

	if adapter, ok := c.adapterProvider.Adapter(procedureName); ok {
		tReq := &transport.Request{
			Caller:    c.cc.Caller(),
			Service:   c.cc.Service(),
			Encoding:  thrift.Encoding,
			Procedure: procedureName,
		}
		res, err := c.adapterClient.Call(ctx, tReq, args, adapter, opts...)
		if err != nil {
			return err
		}

		var ok bool
		result, ok = res.(atomic.Store_Increment_Result)
		if !ok {
			return fmt.Errorf("thrift adapter returned invalid type for procedure, expected 'atomic.Store_Increment_Result', got '%T'", res)
		}

	} else {

		var body wire.Value
		body, err = c.c.Call(ctx, args, opts...)
		if err != nil {
			return
		}

		if err = result.FromWire(body); err != nil {
			return
		}
	}

	err = atomic.Store_Increment_Helper.UnwrapResponse(&result)
	return
}
