// Code generated by thriftrw-plugin-yarpc
// @generated

package extendemptyclient

import (
	context "context"
	fmt "fmt"
	wire "go.uber.org/thriftrw/wire"
	yarpc "go.uber.org/yarpc"
	encoding "go.uber.org/yarpc/api/encoding"
	transport "go.uber.org/yarpc/api/transport"
	thrift "go.uber.org/yarpc/encoding/thrift"
	common "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/common"
	emptyserviceclient "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/common/emptyserviceclient"
	encoding2 "go.uber.org/yarpc/pkg/encoding"
	procedure "go.uber.org/yarpc/pkg/procedure"
	reflect "reflect"
)

// Interface is a client for the ExtendEmpty service.
type Interface interface {
	emptyserviceclient.Interface

	Hello(
		ctx context.Context,
		opts ...yarpc.CallOption,
	) error
}

// New builds a new client for the ExtendEmpty service.
//
// 	client := extendemptyclient.New(dispatcher.ClientConfig("extendempty"))
func New(c transport.ClientConfig, opts ...thrift.ClientOption) Interface {
	return client{
		c: thrift.New(thrift.Config{
			Service:      "ExtendEmpty",
			ClientConfig: c,
		}, opts...),
		adapterProvider: encoding.NopAdapterProvider,

		Interface: emptyserviceclient.New(
			c,
			append(
				opts,
				thrift.Named("ExtendEmpty"),
			)...,
		),
	}
}

// Config is a forwards compatible configuration struct for the ExtendEmpty service.
type Config struct {
	AdapterProvider encoding.AdapterProvider
}

// NewFromConfig builds a new client for the ExtendEmpty service.
func NewFromConfig(cc transport.ClientConfig, cfg Config, opts ...thrift.ClientOption) (Interface, error) {
	const thriftService = "ExtendEmpty"

	thriftClient := thrift.New(thrift.Config{
		Service:      thriftService,
		ClientConfig: cc,
	}, opts...)

	if cfg.AdapterProvider == nil {
		cfg.AdapterProvider = encoding.NopAdapterProvider
	}
	adapterClient, err := encoding2.NewAdapterClient(
		encoding2.AdapterClientConfig{
			ClientConfig: cc,
		},
	)
	if err != nil {
		return nil, err
	}

	return client{
		c:             thriftClient,
		adapterClient: adapterClient,

		Interface: emptyserviceclient.New(
			cc,
			append(
				opts,
				thrift.Named("ExtendEmpty"),
			)...,
		),

		thriftService:   thriftService,
		cc:              cc,
		adapterProvider: cfg.AdapterProvider,
	}, nil
}

func init() {
	yarpc.RegisterClientBuilder(
		func(c transport.ClientConfig, f reflect.StructField) Interface {
			return New(c, thrift.ClientBuilderOptions(c, f)...)
		},
	)
}

type client struct {
	emptyserviceclient.Interface

	c               thrift.Client
	adapterClient   encoding2.AdapterClient
	thriftService   string
	cc              transport.ClientConfig
	adapterProvider encoding.AdapterProvider
}

func (c client) Hello(
	ctx context.Context,
	opts ...yarpc.CallOption,
) (err error) {

	args := common.ExtendEmpty_Hello_Helper.Args()
	procedureName := procedure.ToName(c.thriftService, args.MethodName())

	var result common.ExtendEmpty_Hello_Result

	if adapter, ok := c.adapterProvider.Adapter(procedureName); ok {
		tReq := &transport.Request{
			Caller:    c.cc.Caller(),
			Service:   c.cc.Service(),
			Encoding:  thrift.Encoding,
			Procedure: procedureName,
		}
		res, err := c.adapterClient.Call(ctx, tReq, args, adapter, opts...)
		if err != nil {
			return err
		}

		var ok bool
		result, ok = res.(common.ExtendEmpty_Hello_Result)
		if !ok {
			return fmt.Errorf("thrift adapter returned invalid type for procedure, expected 'common.ExtendEmpty_Hello_Result', got '%T'", res)
		}

	} else {

		var body wire.Value
		body, err = c.c.Call(ctx, args, opts...)
		if err != nil {
			return
		}

		if err = result.FromWire(body); err != nil {
			return
		}
	}

	err = common.ExtendEmpty_Hello_Helper.UnwrapResponse(&result)
	return
}
